# Generated by Django 5.2 on 2025-04-25 17:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('transport_type', models.CharField(choices=[('BUS', 'Bus'), ('TRAIN', 'Train'), ('PLANE', 'Plane'), ('SHIP', 'Ship')], default='BUS', max_length=5)),
                ('transport_name', models.CharField(max_length=100)),
                ('transport_number', models.CharField(max_length=50)),
                ('total_seats', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('available_seats', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Journeys',
                'ordering': ['departure_time'],
                'constraints': [models.CheckConstraint(condition=models.Q(('departure_time__lt', models.F('arrival_time'))), name='departure_before_arrival'), models.CheckConstraint(condition=models.Q(('available_seats__lte', models.F('total_seats'))), name='available_seats_lte_total')],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(max_length=12, unique=True)),
                ('seat_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('PENDING', 'Pending')], default='CONFIRMED', max_length=10)),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
                ('cancelled_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='journey.journey')),
            ],
            options={
                'ordering': ['-booking_time'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=10)),
                ('payment_time', models.DateTimeField(auto_now_add=True)),
                ('payment_details', models.JSONField(default=dict)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='journey.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('is_booked', models.BooleanField(default=False)),
                ('seat_class', models.CharField(default='Standard', max_length=20)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seats', to='journey.booking')),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='journey.journey')),
            ],
            options={
                'ordering': ['seat_number'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_reference'], name='journey_boo_booking_0f5b0f_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'status'], name='journey_boo_user_id_a59dbf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('journey', 'seat_number')},
        ),
    ]
